
version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  
  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/bets.csv
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NAME=SANTIAGO
      - SURNAME=RODRIGUEZ
      - DNI=20023000
      - BIRTH=1999-03-17
      - NUM=24828
    networks:
      - testing_net
    depends_on:
      - server
  client_2:
    container_name: client_2
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/bets.csv
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NAME=PEDRO
      - SURNAME=PEREZ
      - DNI=24769000
      - BIRTH=1999-03-17
      - NUM=3858
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
